### ISSUE TITLE
Deciding what to do with slime—once, and for all

### ISSUE THREAD

**Issue by mistermantas** [PolarGalaxyMC/goggles#1]
Ever since [the 2.1 update](https://github.com/PolarGalaxyMC/goggles/releases/tag/v2.1), slime have been blue. The reason that this is the case, is because the most generic trampolines (that at least I’ve personally seen) are blue. Plus, blue is a nice color!

However, in [the latest version of the pack](https://github.com/PolarGalaxyMC/goggles/releases/tag/v2.4), the color of slime has been reverted to the original green that we’re all familiar with.

My question to you is simple: What should slime look like? Should slime be blue? Should it stay green? Should slime look less sticky and look completely different? I surely don’t know what to do, I need to do some thinking & get feedback.

* * *

## Voting score so far

I’ll keep tally of people who gave feedback on this issue. Most of these folks didn’t sign up for GitHub (basically most Minecraft players).

### Green party

@YourturnGaming, @pphelix, A13xch1, NexoLaw, @callmemantas, Campy

### Blue party

AJ_Shockwave, AbhiTheBoss, mochiu

**Comment by YourturnGaming** [comment]
Personally I would like to keep them green, but also I would like them retexture for example[ cubcon 3D textures. ](http://www.planetminecraft.com/texture_pack/cubcon-textures-preview-64px-172/) http://i.imgur.com/qu82cWs.jpg

**Comment by mistermantas** [comment]
I added a *voting score tally* to the original issue post. I’ll keep it updated as time goes on.

This issue will be closed when all (or most) staff and a few other outsiders give their take on the issue.

**Comment by pphelix** [comment]
I've always valued slime as green naturally. Not just for Minecraft sake but overall when I think of slime I think of green. It should stay green too, as for texture wise I'm not sure but I do like what @YourturnGaming suggested.

**Comment by juliuscaesar1597** [comment]
I think blue is the color that I like the most as slime will be used on the server as mainly trampolines and therefore blue would be a better option for the server to look more realistic.

**Comment by mistermantas** [comment]
And the voting is done. Green is winning, so we’re going with that.
